#!/bin/sh
#
# Copyright (c) 2012 Antti Harri <iku@openbsd.fi>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

set -eu

SUDO=${SUDO:-}

MY_DESTDIR=${DESTDIR}
unset DESTDIR

TMP=$(mktemp -d)
trap "rm -rf \"$TMP\"" 0 1 13 15

# Make required tools using a shell script.
(cd src/usr.bin/make ; CFLAGS="-D_PATH_DEFSYSPATH=\"$TMP\"" ./bootstrap ; mv -f make "$TMP"/; cp -f templates/* "$TMP"/)
(cd src/usr.bin/sort ; ./bootstrap ; mv -f sort "$TMP"/)
(cd src/usr.bin/tsort ; ./bootstrap ; mv -f tsort "$TMP"/)
(cd src/usr.bin/join ; ./bootstrap ; mv -f join "$TMP"/)
cp -f src/usr.bin/lorder/lorder.sh "$TMP"/lorder ; chmod 755 "$TMP"/lorder

MAKE="$TMP/make"
PATH=$TMP:$PATH

# Make sure the tree is clean.
$MAKE clean

(cd libobase && $MAKE)

# Cheat by making a stub mandoc
echo '#!/bin/sh' > "$TMP/mandoc" ; chmod 755 "$TMP/mandoc"
(cd src/usr.bin/mandoc ; env PATH="$PATH" MAKECONF="$TMP/mk.conf" $MAKE)
cp -f src/usr.bin/mandoc/mandoc "$TMP"/
(cd src/usr.bin/yacc ; env PATH="$PATH" MAKECONF="$TMP/mk.conf" $MAKE)
cp -f src/usr.bin/yacc/yacc "$TMP"/

# Make the whole tree using our tools.
env PATH="$PATH" MAKECONF="$TMP/mk.conf" $MAKE

cp -f src/usr.bin/xinstall/xinstall "$TMP"/install
cp -f src/usr.sbin/mtree/mtree "$TMP"/

$SUDO env MAKECONF="$TMP/mk.conf" DESTDIR="$MY_DESTDIR" PATH="$PATH" $MAKE distrib-dirs
$SUDO env MAKECONF="$TMP/mk.conf" DESTDIR="$MY_DESTDIR" PATH="$PATH" $MAKE install
