#!/bin/sh
#
# Copyright (c) 2012 Antti Harri <iku@openbsd.fi>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

set -eu

SUDO=${SUDO:-}

MY_DESTDIR=${DESTDIR}
unset DESTDIR

TMP=$(mktemp -d)
trap "rm -rf \"$TMP\"" 0 1 13 15

# Workaround for Buildroot's flex that doesn't know how to find m4.
export M4=$(which m4)

# Make required tools using a shell script.
(cd src/usr.bin/make ; CFLAGS="-D_PATH_DEFSYSPATH=\"$TMP\"" ./bootstrap ; mv -f make "$TMP"/; cp -f templates/* "$TMP"/)
for i in src/usr.bin/sort src/usr.bin/tsort src/usr.bin/join src/usr.bin/sed; do
	(cd "$i" ; ./bootstrap ; mv -f "$(basename "$i")" "$TMP"/)
done
install -m 755 src/usr.bin/lorder/lorder.sh "$TMP"/lorder

MAKE="$TMP/make"
PATH=$TMP:$PATH

# Make sure the tree is clean.
$MAKE clean

(cd lib/libobase && MAKECONF="$TMP/mk.conf" $MAKE)

# Cheat by making a stub mandoc before making a real one.
echo '#!/bin/sh' > "$TMP/mandoc" ; chmod 755 "$TMP/mandoc"
for i in src/usr.bin/mandoc src/usr.bin/yacc src/usr.bin/lex; do
	(cd "$i"; env PATH="$PATH" MAKECONF="$TMP/mk.conf" $MAKE)
	cp -f "$i/$(basename "$i")" "$TMP"
	(cd "$i"; env PATH="$PATH" MAKECONF="$TMP/mk.conf" $MAKE clean)
done

# Make the whole tree using our tools.
# The MAKE_FLAGS part for MAKECONF makes the variable
# propagate to SUBDIRs.
env	PATH="$PATH"					\
	MAKECONF="$TMP/mk.conf"				\
	$MAKE MAKE_FLAGS=MAKECONF="$TMP/mk.conf"

cp -f src/usr.bin/xinstall/xinstall "$TMP"/install
cp -f src/usr.sbin/mtree/mtree "$TMP"/

$SUDO env						\
	MAKECONF="$TMP/mk.conf"				\
	DESTDIR="$MY_DESTDIR"				\
	PATH="$PATH"					\
	$MAKE						\
		MAKE_FLAGS=MAKECONF="$TMP/mk.conf"	\
		distrib-dirs
		install

